package edu.ualr.fsa;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;

import java.util.Date;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;

import javax.annotation.Resource;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;
import javax.sql.DataSource;

/**
 * Servlet implementation class UploadCSVServlet
 */
@WebServlet("/upload-csv")
@MultipartConfig
public class UploadCSVServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	@Resource(name="jdbc/fsa")// Registered with Tomcat in web.xml & context.xml
    private DataSource ds;
    /**
     * @see HttpServlet#HttpServlet()
     */
    public UploadCSVServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		/**
         * Based on StackOverflow answer
         * https://stackoverflow.com/questions/2422468/how-to-upload-files-to-server-using-jsp-servlet
         * (C) CC BY-SA 3.0 BalusC - https://stackoverflow.com/users/157882/balusc
         */
 
        String networkName = request.getParameter("networkName");
//        String ownerName = request.getUserPrincipal().getName();
        String ownerName = request.getParameter("ownerName");
        Part filePart = request.getPart("userCSV");

        
        // ------- Save File to Work Directory -------
        // Ensure a file was actually uploaded
        if (filePart == null) {
            throw new IOException("No file uploaded.");
        }

        for (String cd : filePart.getHeader("content-disposition").split(";")) {
            if (cd.trim().startsWith("filename")) {
                cd.substring(cd.indexOf('=') + 1).trim().replace("\"", "");
            }
        }
        
//        String fileName = Paths.get(filePart.getSubmittedFileName()).getFileName().toString();
        Long fileSize = filePart.getSize();

        /**
         * Create temporary file on disk at Container TEMPDIR
         * Based on StackOverflow answer
         * https://stackoverflow.com/questions/31255366/how-to-save-generated-file-temporarily-in-servlet-based-web-application
         * (C) CC BY-SA 3.0 BalusC - https://stackoverflow.com/users/157882/balusc
         * 
         * Temp dir path tested on Tomcat. Change if container does not support.
         */
        File fsaWorkDir = (File) getServletContext().getAttribute(ServletContext.TEMPDIR);

        Long currentTime = new Date().getTime();
        File autoGeneratedFile = File.createTempFile(currentTime.toString(),".csv", fsaWorkDir);
        
        // Get Path and String PathString
        Path networkFilePath = autoGeneratedFile.toPath();
        String networkFilePathString = autoGeneratedFile.getPath();
        

        // ------- Stream file to Database -------
        try (InputStream fileStream = filePart.getInputStream()) {
        
            // Replace Empty Temp file with CSV file contents
            Files.copy(fileStream, networkFilePath, StandardCopyOption.REPLACE_EXISTING);

            // Validate all lines in file with Regex
            //List<String> networkLines = Files.readAllLines(networkFilePath);  // Returns all lines with line endings stripped
            
//            for (String line : networkLines) {
//                // See upload_csv.js for equivalent Regex (but including line ending checking)
//                if(!Pattern.matches("^(?:[\\w\\s-\\.@]+,[\\w\\s-\\.@]+(?:,(?:\\d*\\.)?\\d+)?)+$", line)) {
//                    throw new IOException("Incorrect CSV Format");
//                }
//            }
            
            
            // INSERT into database
            NetworkDAO networkDAO = new NetworkDAO();
            networkDAO.insertNetworkFromCSVFile(networkFilePathString, networkName, ownerName); // TODO validate networkName

            // Count lines in file
            Long lineCount = Files.lines(networkFilePath).count();

            // ------- Create HTTP Response -------
            response.setContentType("text/plain");
            response.setCharacterEncoding("UTF-8");
            // TODO write to server log
            response.getWriter().write(fileSize.toString() + " Bytes" + " | " +
                                       lineCount + " lines");
            response.sendRedirect("index.jsp");


        } catch (SQLException e) {
        
            throw new ServletException("Issue contacting the database.", e);
        
        } catch (IOException e) {
            
            throw new ServletException("Issue reading the file. ", e);
            
        } finally {
        
            // Delete generated CSV file from server disk
            autoGeneratedFile.delete();
            
        }
	}

}
